name: Post-release gopass deployement

on:
  release:
    types:
      - created

jobs:
  CD:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
        
    - name: Ubuntu Dependencies
      run: sudo apt-get install --yes git gnupg2

    - run: git config --global user.name "Gopass Releaser"
    - run: git config --global user.email foo.bar@example.org
    
    - name: Generate release-notes
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      run: |
          go run helpers/postrel/main.go
